### (2) Numpy array의 생김새

In [ ]:
import numpy

In [ ]:
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [ ]:
array1

In [ ]:
type(array1)

In [ ]:
#요소가 몇개가 있는지 알아보자!
array1.shape

In [ ]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
# nd : N-dimensional
type(array2)

In [ ]:
array2

In [ ]:
 #2차원 Array! 세로길이 3 가로길이 4
array2.shape

In [ ]:
#총 요소의 개수
array1.size

In [ ]:
array2.size

### (4) 모듈 별명 지어주기

In [ ]:
import numpy 

array1 = numpy.full(6,0)
array2 = numpy.zeros(6)
array3 = numpy.full(6,6)
array4 = numpy.ones(9)
array5 = numpy.random.random(6)
array6 = numpy.random.random(10)
print(array1)
print(array2)
print(array3)
print(array4)
print(array5)
print(array6)

In [ ]:
import numpy as np

array1 = np.full(6,0)
array2 = np.zeros(6)
array3 = np.full(6,6)
array4 = np.ones(9)
array5 = np.random.random(6)
array6 = np.random.random(10)
print(array1)
print(array2)
print(array3)
print(array4)
print(array5)
print(array6)

### (9) 인덱싱, 슬라이싱


In [ ]:
import numpy as np

In [ ]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [ ]:
array1[0]

In [ ]:
array1[2]

In [ ]:
array1[-1]

In [ ]:
array1[-2]

In [ ]:
#리스트로 인덱싱
array1[[1,3,4]]

In [ ]:
#Numpy array로 인덱싱 가능
array2 = np.array([2,1,3])

In [ ]:
array1[array2]

In [ ]:
array1[2:7]

In [ ]:
array1[0:7]

In [ ]:
array1[:7]

In [ ]:
array1[2:]

In [ ]:
#하나씩 건너뛰기
array1[2:11:2]

In [ ]:
array1[2:11:3]

### (6) Numpy 기본 연산


In [2]:
import numpy as np

In [3]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [4]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# Numpy를 안쓰고 모든 값에 X2하기
for i in range(len(array1)):
    array1[i] = 2 * array1[i]

In [6]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Numpy로 사용하면 이렇게 간단하다 !

array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
array1 +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [10]:
# 리스트 끼리 더하기 가능! (기본 파이썬 쓰려면 for문 써야 한다.)
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [11]:
#곱하기도 가능
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

### (9) Numpy 불린(Boolean) 연산

In [12]:
import numpy as np 

In [13]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [14]:
# 4보다 작은 놈들에만 False 들어간다
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [15]:
# 짝수들에만 True가 들어가고 나머지는 모두 False로 들어간다
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [16]:
booleans = np.array([True,True,False,True,True,False,True,True,True,False,True])

In [18]:
# True인 값들의 인덱스들만 반환
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [22]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [24]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])